name: Get latest release version
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch release version
        run: |
           cp NostalgiaForInfinityX.py user_data/strategies
           cp NostalgiaForInfinityX2.py user_data/strategies
           curl -O https://raw.githubusercontent.com/dida1990/freqtrade-blacklist/main/blacklist-kucoin-binance.json && \
           mv blacklist-kucoin-binance.json configs/
          #curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/NostalgiaForInfinityX.py && \
           #cp NostalgiaForInfinityX.py user_data/strategies
          #curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/NostalgiaForInfinityX2.py && \
          #cp NostalgiaForInfinityX2.py user_data/strategies
          #curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/configs/blacklist-binance.json && \
          #mv blacklist-binance.json user_data/strategies/NostalgiaForInfinityX
          #curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/configs/pairlist-volume-binance-usdt.json && \
          #mv pairlist-volume-binance-usdt.json user_data/strategies/NostalgiaForInfinityX
          #curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/configs/blacklist-kucoin.json && \
          #mv blacklist-kucoin.json user_data/strategies/NostalgiaForInfinityX
          #curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/configs/pairlist-volume-kucoin-usdt.json && \
          #mv pairlist-volume-kucoin-usdt.json user_data/strategies/NostalgiaForInfinityX
          #curl -O https://raw.githubusercontent.com/dida1990/freqtrade-blacklist/main/blacklist-kucoin-binance.json && \
          #mv blacklist-kucoin-binance.json configs/
      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -am "Update NostalgiaForInfinityX2 Strategy"
          git push
      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        if: steps.git-check.outputs.modified == 'true'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Config Files updated.
